#!/usr/bin/python3
""" learning about json and pythn"""

import json

def main():
    with open("got.json", "r") as gameofthrone:
        #myjson = gameofthrone.read()
        mygot = json.load(gameofthrone)
    print(mygot['url'])
    print(type(mygot))
    #print(myjson)
    #print(type(myjson))

main()
