---
-name: Playing with switches and ansible
 hosts: cloudswitches
 gather_facts: no
 vars: 
         ansible_connection: network_cli
         ansible_network_os: eos
         ansible_become: yes
         ansible_user: admin
         ansible_ssh_pass: alta3
 tasks:
         -

